# Generated by Django 5.1 on 2024-09-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='productname',
        ),
        migrations.AddField(
            model_name='product',
            name='categary',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
