# Generated by Django 5.1 on 2024-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_name_product_productname_product_categary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
